### ISSUE TITLE
Encoding conversion problem

### ISSUE THREAD

**Issue by matthieuRicaudDussarget** [cmarchand/xslCompiler-maven-plugin#1]
I have an xsd source file starting with 
<?xml version="1.0" encoding="UTF-8"?>

It has french accents text, but when compiling the maven project the accents are away and I get this error (validating NVDL file which call this XSD) : 
[JING] Invalid Byte 2 of 3-bytes UTF-8 sequence

**Comment by cmarchand** [comment]
Encoding was not specified on output files, so it was using platform encoding.
Solved with commit #099b949
