### ISSUE TITLE
Update Saxon dependency

### ISSUE THREAD

**Issue by mricaud** [cmarchand/xslCompiler-maven-plugin#8]
It seems like the plugin can not be used with version of Saxon after 9.8.
Saxon api has changed since this version, it would be great to be up to date with last saxon version :)

**Comment by hamdikarray** [comment]
Hello @cmarchand , i do the job for saxon 10 compatibility (saxon 9.8 still working): can i do a pull request ?

**Comment by cmarchand** [comment]
Sure !
Thanks !
Christophe

**Comment by hamdikarray** [comment]
Hello @cmarchand,
Thanks. 
The release build takes a lot of time ?

**Comment by cmarchand** [comment]
No, I sleep...
I'm working on moving to Java 11

**Comment by cmarchand** [comment]
Release 2.0.0 has been published, wait for sonatype / maven central synchro.

It's a major release because plugin is now compiled in Java11, and so you must use a Java 11 to run maven on your projects.
